DEFRA/ffc-demo-payment-web

- Jenkinsfile
- README.md
- app/config/index.js
- app/config/okta.js
- app/plugins/auth.js
- app/plugins/router.js
- app/routes/home.js
- app/routes/okta.js
- app/server.js
- app/views/home.njk
- docker-compose.yaml
- helm/ffc-demo-payment-web/templates/deployment.yaml
- helm/ffc-demo-payment-web/values.yaml
- package-lock.json
- package.json
- test/routes/home.test.js
https://eaflood.atlassian.net/browse/PSD-586
> Only allow authenticated users access

- .gitignore
- Jenkinsfile
- README.md
- app/config/index.js
- app/models/payments-view-model.js
- app/plugins/error-pages.js
- app/services/payment-schedule-service.js
- docker-compose.yaml
- helm/ffc-demo-payment-web/templates/deployment.yaml
- helm/ffc-demo-payment-web/values.yaml
- package.json
- test/routes/payments.test.js
https://eaflood.atlassian.net/browse/PSD-666
Replace stubbed retrieval of payment schedules with call to API
> Integrate Payments API

- Jenkinsfile
- README.md
- app/config/get-okta-config.js
- app/plugins/auth.js
- app/plugins/okta-custom-provider.js
- app/routes/payments.js
- app/services/payment-schedule-service.js
- docker-compose.test.yaml
- docker-compose.yaml
- helm/ffc-demo-payment-web/templates/deployment.yaml
- helm/ffc-demo-payment-web/values.yaml
- package-lock.json
- package.json
https://eaflood.atlassian.net/browse/PSD-687
The access token from Okta for the custom scope should be passed on to
the payment services API
> Pass access token onto API

- app/plugins/error-pages.js
- app/views/403.njk
- package.json
https://eaflood.atlassian.net/browse/PSD-669
> Support user authorisation

- Dockerfile
- README.md
- docker-compose.yaml
- package.json
https://eaflood.atlassian.net/browse/PSD-727
> Use DockerHub parent image

- Jenkinsfile
- package.json
https://eaflood.atlassian.net/browse/PSD-738
> Library version incremented

- Jenkinsfile
- helm/ffc-demo-payment-web/deployment-config-keys.txt
- helm/ffc-demo-payment-web/templates/config-map.yaml
- helm/ffc-demo-payment-web/templates/container-secret.yaml
- helm/ffc-demo-payment-web/templates/service.yaml
- helm/ffc-demo-payment-web/values.yaml
- package.json
https://eaflood.atlassian.net/browse/PSD-843
Add list of keys to file that will populate Helm chart values during deploy
> Move Helm values to Azure App Configuration

- Jenkinsfile
- package.json
- sonar-project.properties
https://eaflood.atlassian.net/browse/PSD-860
> SonarCloud CI added

- helm/ffc-demo-payment-web/templates/developer-rolebinding.yaml
- package.json
https://eaflood.atlassian.net/browse/PSD-692
> Rolebinding only on PR deployment

- README.md
- app/index.js
- app/services/app-insights.js
- docker-compose.yaml
- helm/ffc-demo-payment-web/templates/config-map.yaml
- helm/ffc-demo-payment-web/templates/container-secret.yaml
- helm/ffc-demo-payment-web/values.yaml
- package-lock.json
- package.json
https://eaflood.atlassian.net/browse/PSD-887
> Add Application Insights

- app/services/app-insights.js
- package-lock.json
- package.json
https://eaflood.atlassian.net/browse/PSD-924
> Log when App Insights is active

- README.md
- package-lock.json
- package.json
https://eaflood.atlassian.net/browse/PSD-970
> Replace node-sass with (dart) sass

- .secrets.baseline
- app/config/index.js
- app/plugins/views.js
- app/views/layout.njk
- app/views/tagManager/bodyContent.njk
- app/views/tagManager/headContent.njk
- docker-compose.yaml
- helm/ffc-demo-payment-web/templates/config-map.yaml
- helm/ffc-demo-payment-web/values.yaml
- package-lock.json
- package.json
https://eaflood.atlassian.net/browse/PSD-1004
> Add Google Analytics to demo web

- Jenkinsfile
- helm/ffc-demo-payment-web/Chart.yaml
- package.json
https://eaflood.atlassian.net/browse/PSD-1043
> Helm library version update

- package-lock.json
- package.json
https://eaflood.atlassian.net/browse/PSD-1265
> Fix dependabot vulnerabilities

- .azuredevops/build.yaml
- helm/ffc-demo-payment-web/Chart.yaml
- helm/ffc-demo-payment-web/templates/_container.yaml
- helm/ffc-demo-payment-web/templates/config-map.yaml
- helm/ffc-demo-payment-web/templates/container-secret.yaml
- helm/ffc-demo-payment-web/templates/deployment.yaml
- helm/ffc-demo-payment-web/templates/ingress.yaml
- helm/ffc-demo-payment-web/templates/service.yaml
- helm/ffc-demo-payment-web/values.yaml
- package-lock.json
- package.json
This pr includes the changes to update helm charts for ADP and added ADO build pipeline.
https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/231730
> 231730: Updated helm charts for ADP and added ADO build pipeline

- .azuredevops/build.yaml
- Dockerfile
- Jenkinsfile
- appConfig/appConfig.snd1.json
- helm/ffc-demo-payment-web/Chart.yaml
- helm/ffc-demo-payment-web/templates/config-map.yaml
- helm/ffc-demo-payment-web/templates/container-secret.yaml
- helm/ffc-demo-payment-web/values.yaml
- package-lock.json
- package.json
This PR contains the below changes.
- Updated build pipeline to include appConfig ingestion
- Updated helm templates for implementing app config provider
AB#254838
> 254838: Updated build pipeline, Updated helm template

- catalog-info.yaml
- docs/index.md
- mkdocs.yml
[AB#265553](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/265553)
> 278625: basic techdocs

- jest.config.js
- package-lock.json
- package.json
- test/unit/config/index.test.js
- test/unit/index.test.js
- test/unit/model/payments-view-model.test.js
- test/unit/plugins/error-pages.test.js
- test/unit/plugins/logging.test.js
- test/unit/plugins/router.test.js
- test/unit/plugins/views.test.js
- test/unit/routes/healthy.test.js
- test/unit/routes/healthz.test.js
- test/unit/routes/home.test.js
- test/unit/routes/payments.test.js
- test/unit/routes/static.test.js
- test/unit/server.test.js
- test/unit/services/app-insights.test.js
- test/unit/services/payment-schedule-service.test.js
This PR contains the fixes to increase code coverage to >90%
[AB#282429](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/282429)
> 282429: Code coverage fix to >90%

- .azuredevops/build.yaml
- helm/ffc-demo-payment-web/values.yaml
- package-lock.json
- package.json
Removed duplicate values defined in the values.yaml files.   Also removed values which are the same as the defaults in the helm-library.
Information defined in the app config files will not be duplicated in the values.yaml file
Tested changes against SND1 Cluster and Demo Apps are still working successfully.
> 277457: Remove duplicate values defined in the values.yaml files for each repo

- .azuredevops/build.yaml
- package.json
[AB#306902](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/306902)
What this PR does / why we need it:
variableGroups: 
- ffc-demo-payment-web-<environment>
Testing
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=467223&view=results
Checklist (please delete before completing or setting auto-complete)
[ ] Story Work items associated (not Tasks)
[x] Successful testing run(s) link provided
[x] Title pattern should be {work item number}: {title}
[x] Description covers all the changes in the PR
[ ] This PR contains documentation
[ ] This PR contains tests
> 306902: Simplify Variable Group Naming in remaining services

- README.md
- helm/ffc-demo-payment-web/values.yaml
- package-lock.json
- package.json
Helm cleanup and Readme updates
> Helm cleanup and Readme updates

- .azuredevops/build.yaml
- package.json
*A brief description of changes being made*
*Link to the relevant work items: 
[AB#323021](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/323021)
Simplify the variable import from variable groups specific to environment
*Any specific actions or notes on review?*
*Any relevant testing information and pipeline runs.*
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=498715&view=results
Have you updated any related templates, repositories or dependencies for new changes? We must ensure any dependencies like Software Templates are updated to include the latest changes to be scaffolded for all services where applicable.
> 323021: Variable Import

- .gitignore
- package.json
[AB#337921](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/337921)
Remove auth from .gitignore to track the changes of auth folder in repo
auth removed from .gitignore file
*Any relevant testing information and pipeline runs.*
> 337921: Remove auth from exclusions in .gitignore

- .azuredevops/build.yaml
- appConfig/appConfig.snd4.yaml
- package.json
Added snd4 file into appConfig folder
[AB#334259](https://dev.azure.com/defragovuk/DEFRA-FFC/_sprints/taskboard/DEFRA-FFC%20Team%20Fab/DEFRA-FFC/Platform/Fab/Sprint16?workitem=334259)
> 33429: Snd4 appConfig

- appConfig/appConfig.prd1.yaml
- appConfig/appConfig.pre1.yaml
- package.json
[#AB296232](https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/296232/)
Adds appConfig files for prd1 & pre1 to resolve pipeline failures
> 296232 : Adds appConfig files for prd1 & pre1
